#lifted from: https://github.com/angular/angular-seed/blob/master/.travis.yml
language: node_js
node_js:
  - '0.8'
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma@0.8.3
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - npm install -g bower grunt-cli
  - bower install
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
